apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-emotibotsoundbox
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: 
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis-emotibotsoundbox
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: 172.16.101.70/hrbot/redis:latest
        envFrom:
        - configMapRef:
            name: emotibotsoundbox
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: 1
            memory: 5Gi

        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 

  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-emotibotsoundbox
spec:
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-emotibotsoundbox