# coding=UTF-8

ANSIBLE_TARGET_PATH = 'target'
ANSIBLE_TARGET_HOST_PATH = ANSIBLE_TARGET_PATH + '/host.yaml'
ANSIBLE_TARGET_MAIN_PATH = ANSIBLE_TARGET_PATH + '/main.yaml'

ANSIBLE_TEMPLATE_DIR = 'template'
ANSIBLE_TEMPLATE_INITJOB_PATH = ANSIBLE_TEMPLATE_DIR + '/initJob/initJob.yaml.template'
ANSIBLE_TEMPLATE_PREJOB_DIR = ANSIBLE_TEMPLATE_DIR + '/preJob'
ANSIBLE_TEMPLATE_MAINJOB_PATH = ANSIBLE_TEMPLATE_DIR + '/mainJob/mainJob.yaml.template'
ANSIBLE_TEMPLATE_AFTERJOB_DIR = ANSIBLE_TEMPLATE_DIR + '/afterJob'
ANSIBLE_TEMPLATE_KUBERNETES_DIR = ANSIBLE_TEMPLATE_DIR + '/kubernetes'

ANSIBLE_TARGET_INITJOB_PATH = ANSIBLE_TARGET_PATH + '/initJob/initJob.yaml'
ANSIBLE_TARGET_PREJOB_DIR = ANSIBLE_TARGET_PATH + '/preJob'
ANSIBLE_TARGET_MAINJOB_PATH = ANSIBLE_TARGET_PATH + '/mainJob/mainJob.yaml'
ANSIBLE_TARGET_AFTERJOB_DIR = ANSIBLE_TARGET_PATH + '/afterJob'
ANSIBLE_TARGET_KUBERNETES_DIR = ANSIBLE_TARGET_PATH + '/kubernetes'

HOST_KEY = 'HOST'
USER_KEY = 'USER'
IP_KEY = 'HOST_IP'
PASSWORD_KEY = 'PASSWORD'

K8S_HOST_KEY = 'K8S_HOST'
K8S_USER_KEY = 'K8S_USER'
K8S_IP_KEY = 'K8S_HOST_IP'
K8S_PASSWORD_KEY = 'K8S_PASSWORD'

PRE_JOB_LIST_KEY = 'PRE_JOB_LIST'
MAIN_JOB_LIST_KEY = 'MAIN_JOB_LIST'
MAIN_PRIORITIZED_JOB_LIST_KEY = 'MAIN_PRIORITIZED_JOB_LIST'
AFTER_JOB_LIST_KEY = 'AFTER_JOB_LIST'

PROJECT_HOME_DIR_KEY = 'PROJECT_HOME_DIR'


