#generate

HOST: localhost
HOST_IP: localhost
USER: deployer
PASSWORD: Emotibot1

K8S_HOST: k8s_host
K8S_HOST_IP: 172.16.101.91
K8S_USER: deployer
K8S_PASSWORD: Emotibot1

CONFIG_NAME: emotibotsoundbox
PROJECT_NAME: emotibotsoundbox
MAIN_PRIORITIZED_JOB_LIST: consul,mysql,redis,mongodb
#PRE_JOB_LIST: mysql,houta,multicustomer,mongodb
#MAIN_JOB_LIST: mysql,bot-factory-backend-service,consul,houta,redis,simulate-dc,task-engine,multicustomer,mongodb
#AFTER_JOB_LIST: consul,houta
PRE_JOB_LIST: 
MAIN_JOB_LIST: mongodb
AFTER_JOB_LIST: 

# change for diff env
KUBECTL_COMMOND: /usr/local/bin/kubectl
PROJECT_HOME_DIR: /home/deployer/yanbinwa/ansible


#config

##mysql
MYSQL_USER: root
MYSQL_PASSWORD: password

#init job

#preJob

##consul
CONSUL_CONFIG_FILE: 

##mysql
MYSQL_CONFIG_FILE: package/mysql/my.cnf
MYSQL_SH_FILE: package/mysql/docker-entrypoint.sh
MYSQL_SQL_FILE: package/mysql/emotibot.sql

#main job

##bot-factory-backend-service
BOT_FACTORY_BACKEND_SERVICE_IMAGE: 172.16.101.70/hrbot/bot-factory-backend-service:4351bad
BOT_FACTORY_BACKEND_SERVICE_SERVICENAME: bot-factory-backend-service
BOT_FACTORY_BACKEND_SERVICE_TARGETPORT: 15501
BOT_FACTORY_BACKEND_SERVICE_PORT: 15501

##consul
CONSUL_IMAGE: 172.16.101.70/hrbot/consul:0.8.4
CONSUL_SERVICENAME: consul
CONSUL_TARGETPORT: 8500
CONSUL_PORT: 8500
CONSUL_NODEPORT: 31001

##houta
HOUTA_IMAGE: 172.16.101.70/hrbot/houta:c9908dd_task-engine
HOUTA_SERVICENAME: houta
HOUTA_TARGETPORT: 80
HOUTA_PORT: 80
HOUTA_NODEPORT: 31017

##mysql
MYSQL_IMAGE: 172.16.101.70/hrbot/mysql:5.7
MYSQL_SERVICENAME: mysql
MYSQL_TARGETPORT: 3306
MYSQL_PORT: 3306
MYSQL_NODEPORT: 31018

##redis
REDIS_IMAGE: 172.16.101.70/hrbot/redis:latest
REDIS_SERVICENAME: redis
REDIS_TARGETPORT: 6379
REDIS_PORT: 6379

##simulate_dc
SIMULATE_DC_IMAGE: 172.16.101.70/hrbot/fake-dc:4180625
SIMULATE_DC_SERVICENAME: simulate-dc
SIMULATE_DC_TARGETPORT: 80
SIMULATE_DC_PORT: 10901

##task-engine
TASK_ENGINE_IMAGE: 172.16.101.70/hrbot/task-engine:34e4f6b
TASK_ENGINE_SERVICENAME: task-engine
TASK_ENGINE_TARGETPORT: 14101
TASK_ENGINE_PORT: 14101

##multicustomer
MULTICUSTOMER_IMAGE: 172.16.101.70/hrbot/multicustomer:febb902
MULTICUSTOMER_SERVICENAME: multicustomer
MULTICUSTOMER_TARGETPORT_1: 9011
MULTICUSTOMER_PORT_1: 14501
MULTICUSTOMER_TARGETPORT_2: 873
MULTICUSTOMER_PORT_2: 14502

##mongodb
MONGODB_IMAGE: 172.16.101.70/hrbot/mongo:3.2.8
MONGODB_SERVICENAME: mongodb
MONGODB_TARGETPORT: 27017
MONGODB_PORT: 27017

##nlu
NLU_IMAGE: 172.16.101.70/hrbot/changhong-nlu:2017092600
NLU_SERVICENAME: nlu
NLU_TARGETPORT: 13901
NLU_PORT: 13901

##solr-etl-agent
SOLR_ETL_AGENT_IMAGE: 172.16.101.70/hrbot/task-engine:34e4f6b
SOLR_ETL_AGENT_SERVICENAME: task-engine
SOLR_ETL_AGENT_TARGETPORT: 14101
SOLR_ETL_AGENT_PORT: 14101

#afterJob

##houta

HOUTA_WORD_BANK_CHECK_FILE: package/houta/word_bank_check.php
HOUTA_INTENT_CHECK_FILE: package/houta/intent_check.php
HOUTA_MAPPING_TABLE_UPLOAD_FILE: package/houta/mapping_table_upload.php