apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-emotibotsoundbox
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mysql-emotibotsoundbox
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mysql
        image: 172.16.101.70/hrbot/mysql:5.7
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: emotibotsoundbox
                key: MYSQL_ROOT_PASSWORD
        envFrom:
        - configMapRef:
            name: emotibotsoundbox
        ports:
          - containerPort: 3306
        resources:
          limits:
            cpu: 1
            memory: 2Gi

        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
        - mountPath: /etc/mysql/my.cnf
          name: mysqlconfig
        - mountPath: /var/lib/mysql
          name: mysqldata
        - mountPath: /usr/local/bin/docker-entrypoint.sh
          name: sh
        - mountPath: /var/local/database/emotibot.sql
          name: sql
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 
       - name: mysqlconfig
         hostPath:
           path: /servicedata/emotibotsoundbox/mysql/config/my.cnf
       - name: mysqldata
         hostPath:
           path: /servicedata/emotibotsoundbox/mysql/data
       - name: sh
         hostPath:
           path: /servicedata/emotibotsoundbox/mysql/config/docker-entrypoint.sh
       - name: sql
         hostPath:
           path: /servicedata/emotibotsoundbox/mysql/config/emotibot.sql

      nodeSelector:
        kubernetes.io/hostname: 172.16.101.91

---
apiVersion: v1
kind: Service
metadata:
  name: None
  labels:
    app: mysql-emotibotsoundbox
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31018
  selector:
    app: mysql-emotibotsoundbox

